mgb.spellingtest.web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpellingTest.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

    }
}

mgb.spellingtest.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace deleteme.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

mgb.spellingtest.web/Controllers/SpellingTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;
using System.Threading.Tasks;
using System.Speech.Synthesis;
using mgb.spellingtest.web.SpellingTestReference;


namespace SpellingTest.Controllers
{
    public class SpellingTestController : Controller
    {
                

        public ActionResult GetUser()
        {
            // Get List of users


            return View();
        }

        //[HttpPost]
        public ActionResult SelectAction()
        {
            return View();
        }

        //[HttpPost]
        public ActionResult ActionRouting(string Options)
        {
            switch (Options)
            {
                case "1":

                    // Get test list
                    SpellingTestServiceClient client = new SpellingTestServiceClient();
                    List<Test> testList = client.GetTestList("whatever").ToList();

                    // Display test list
                    return View("SelectTest", testList);
                case "2":
                    return View("RetakeOldTest");
                case "3":
                    return View("ReviewOldTest");
                default:
                    return View("SelectTest");
            }
        }


        //[HttpPost]
        public ActionResult GetTestData( /*string TestId*/ )
        {
            // Get test data for the given TestId

            // Begin the test
            return RedirectToAction("GiveTest");
        }


        //[HttpPost]
        public ActionResult GiveTest( /*receives an object with test data in it */ )
        {
            // check to see if all questions in the test data object have been answered.
            // If all answered, redirect
            //else, return the view, passing in the object again

            var testFinished = false;

            if (!testFinished)
            {
                return View();
            }
            else
            {
                return RedirectToAction("TestComplete");
            }
        }


       // [HttpPost]
        public ActionResult TestComplete()
        {
            return View();
        }

        
       // [HttpPost]
        public ActionResult Speak(string textToSpeak)
        {

            var t = new Thread(() =>
            {
                SpeechSynthesizer synth = new SpeechSynthesizer();
                synth.SelectVoiceByHints(VoiceGender.Male, VoiceAge.Adult, 0, new System.Globalization.CultureInfo("en-US"));
                synth.Speak(textToSpeak);
                synth.SetOutputToNull();

            });

            t.Start();
            t.Join();

            return RedirectToAction("GiveTest");
        }
    }
}

mgb.spellingtest.web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

mgb.spellingtest.web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

mgb.spellingtest.web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

mgb.spellingtest.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Spelling Test</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Spelling Test", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        Hello, <span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year Mike Bingham</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

mgb.spellingtest.web/Views/SpellingTest/GetUser.cshtml
@{
    ViewBag.Title = "Log In";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                Please enter your user name.
            </p>
        </div>
    </section>
}

@section Scripts
{
    <script type="text/javascript">
        function validatePage()
        {            
            if (document.login.UserName.value == "")
            {
                alert("Please enter your user name.");
                document.login.UserName.focus();
                return false;
            }
        }

        function init()
        {
            document.login.UserName.focus();
        }

        window.onload = init;
    </script>

}

@using (Html.BeginForm("SelectAction", "SpellingTest", FormMethod.Post, new { name= "login", id="login", enctype = "multipart/form-data", onsubmit = "return validatePage();"}))
{
    <table>
        <tr>
            <td>User Name:</td>
            <td><input type ="text" id="UserName" name ="UserName" title="Please enter your user name"/></td>
            <td><input type="button" name="UserLookup" value="Lookup" /></td>
        </tr>
        <tr>
            <td><input type ="submit" name ="submit" value ="Log In" /></td>
        </tr>
    </table>    
}

mgb.spellingtest.web/Views/SpellingTest/GiveTest.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Spelling Test</h2>

@using (Html.BeginForm("GiveTest", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{    
    <table>
        <tr>
            <td>Enter the word</td>
            <td><input type="text" name="word" id="word" /></td>
        </tr>
    </table>
    
    <input type ="submit" name ="submit" value ="Submit" />
}

@using (Html.BeginForm("Speak", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{    
    <input type="hidden" name ="TextToSpeak" value="Spell the word elephant." />
    
    <input type ="submit" name ="repeatword" value ="Repeat Word" />
}

mgb.spellingtest.web/Views/SpellingTest/RetakeOldTest.cshtml
@{
    ViewBag.Title = "RetakeOldTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Retake Old Test</h2>
@using (Html.BeginForm("ActionRouting", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{    
    <input type ="submit" name ="submit" value ="Submit" />
}

mgb.spellingtest.web/Views/SpellingTest/ReviewOldTest.cshtml
@{
    ViewBag.Title = "ReviewOldTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Review Old Test</h2>
@using (Html.BeginForm("ActionRouting", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{    
    <input type ="submit" name ="submit" value ="Submit" />
}

mgb.spellingtest.web/Views/SpellingTest/SelectAction.cshtml
@{
    ViewBag.Title = "Select Action";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Student Options</h2>

@using (Html.BeginForm("ActionRouting", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.RadioButton("Options", 1, true) @:New Test
    <br />
    @Html.RadioButton("Options", 2, false) @:Retake old test   
    <br />
    @Html.RadioButton("Options", 3, false) @:Review words missed on old test       
    <br />
    <input type ="submit" name ="submit" value ="Submit" />
}

mgb.spellingtest.web/Views/SpellingTest/SelectTest.cshtml
@using mgb.spellingtest.web.SpellingTestReference;
@model List<Test>

@{
    ViewBag.Title = "SelectTest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select a test to take</h2>
@using (Html.BeginForm("GetTestData", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>    

        @foreach (Test singleTest in @Model)
        {               
            <tr>
                <td>@Html.ActionLink(@singleTest.Name,"GetTestData","SpellingTest")</td>
                <td>@Html.ActionLink(@singleTest.Description,"GetTestData","SpellingTest")</td>
            </tr>
        }

    </table>
    
    <input type ="submit" name ="submit" value ="Submit" />
}

mgb.spellingtest.web/Views/SpellingTest/TestComplete.cshtml
@{
    ViewBag.Title = "TestComplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TestComplete</h2>
@using (Html.BeginForm("SelectAction", "SpellingTest", FormMethod.Post, new { enctype = "multipart/form-data" }))
{    
    <input type ="submit" name ="submit" value ="Finish" />
}